name: Node CI

on:
  pull_request:
      branches:
      - develop
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        curl https://install.meteor.com/ | sh
        ls
        meteor build ./build --architecture os.linux.x86_64
      env:
        CI: true
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: ./build
